// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGbaJ8Attp-1ogdcuO11tLz_Qef5Ylmhg',
    appId: '1:357990422500:web:742c005805601af67e59f1',
    messagingSenderId: '357990422500',
    projectId: 'kidsplay-8132',
    authDomain: 'kidsplay-8132.firebaseapp.com',
    storageBucket: 'kidsplay-8132.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvSRr2MpSV3IjRvl8GtZ0ymjre9AuuxF0',
    appId: '1:357990422500:android:dc590e48a04d57407e59f1',
    messagingSenderId: '357990422500',
    projectId: 'kidsplay-8132',
    storageBucket: 'kidsplay-8132.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9wF1pddR0-TAYKpIQwLttKYUO_G5zCS4',
    appId: '1:357990422500:ios:5a39b6a03a84d0e17e59f1',
    messagingSenderId: '357990422500',
    projectId: 'kidsplay-8132',
    storageBucket: 'kidsplay-8132.firebasestorage.app',
    iosBundleId: 'com.kidsplay.app.testProject',
  );
}
